version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: etl_test
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: 19460633
    ports:
      - '5432:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
